### ISSUE TITLE
Enabling bolt connector 

### ISSUE THREAD

**Issue by stimon** [monarch-initiative/scigraph-docker#10]
Is it possible to enable Neo4j's bolt connector through the config? I have tried adding the correspondent settings:
```yaml
neo4jConfig:
    dump_configuration : true
    dbms.pagecache.memory : 64g
    dbms.transaction.timeout: 3m
    dbms.connector.bolt.enabled: true
    dbms.connector.bolt.listen_address: 0.0.0.0:7688
```
But it is still not reachable from Neo4j Desktop
